export const holidayData = [
  { id: 1, variant: "click", front: "Bad Special Effects", back: "Take a sip" },
  { id: 2, variant: "click", front: "Melissa Joan Hart", back: "Take a shot" },
  { id: 3, variant: "click", front: "Baking Fight", back: "Take a shot" },
  {
    id: 4,
    variant: "click",
    front: "Related to Santa",
    back: "Finish your Drink",
  },
  { id: 5, variant: "click", front: "Estranged Parent", back: "Take a sip" },
  {
    id: 6,
    variant: "click",
    front: "Workaholic Learns to Love",
    back: "Finish your Drink",
  },
  { id: 7, variant: "click", front: "Ghost", back: "Give a Sip" },
  { id: 8, variant: "click", front: "Precocious Child", back: "Take a Sip" },
  { id: 9, variant: "click", front: "Magical Weirdo", back: "Be Magical" },
  { id: 10, variant: "click", front: "Contest", back: "Take a sip" },
  { id: 11, variant: "click", front: "Car Trouble", back: "Give a sip" },
  {
    id: 12,
    variant: "click",
    front: "Forced to kiss - sparks fly",
    back: "Finish your Drink",
  },
  {
    id: 13,
    variant: "click",
    front: "Someone Doesn't Like Christmas",
    back: "Take a Sip",
  },
  {
    id: 14,
    variant: "click",
    front: "Need to Save Family Business",
    back: "Take a Sip",
  },
  { id: 15, variant: "click", front: "Time Travel", back: "Finish your Drink" },
];
